# Copyright 2019 Google Inc.  All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "com_google_cloud_examples_vision")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "gapic-generator-cpp",
    strip_prefix = "gapic-generator-cpp-master",
    urls = ["https://github.com/googleapis/gapic-generator-cpp/archive/master.zip"],
)

http_archive(
    name = "googleapis",
    strip_prefix = "googleapis-master",
    urls = ["https://github.com/googleapis/googleapis/archive/master.zip"],
)

load("@gapic-generator-cpp//:repositories.bzl", "com_google_gapic_generator_cpp_repositories")

com_google_gapic_generator_cpp_repositories()

#load("@gapic-generator-cpp//rules_gapic/cpp:cc_gapic.bzl", "cc_gapic_library")
